### ISSUE TITLE
artwork -> sourcecode

### ISSUE THREAD

**Issue by mchurch-rpc** [mchurch-rpc/rfc9410-github-practice-madison#8]
We have updated artwork elements to sourcecode throughout 
the document. Please review the "type" attribute of each sourcecode element
in the XML file to ensure correctness. If the current list of preferred
values for "type" (https://www.rfc-editor.org/materials/sourcecode-types.txt) does not
contain an applicable type, then feel free to let us know. Also, it is
acceptable to leave the "type" attribute not set.

**Comment by sginoza** [comment]
So this one would actually need to be a PR to highlight the changes bc there FYI AQs in their current form no longer exist.  

for this exercise, this AQ isn't really relevant since we're working in the .original file (i.e., there is no sourcecode).  

Seemingly we can close this one with no action.
